version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: bank-db
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - bank-data:/var/lib/postgresql/data

volumes:
  bank-data:
